name: CI

on:
  push:
    branches: [main, master]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - nightly
    name: ${{ matrix.rust }}
    env:
      CARGO_FLAGS: ${{ matrix.rust == 'nightly' && '--all-features' || '' }}
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: cargo build ${{ env.CARGO_FLAGS }}
      - name: Test
        run: cargo test --all-targets ${{ env.CARGO_FLAGS }}
      - name: Doc
        run: cargo doc --no-deps ${{ env.CARGO_FLAGS }}
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets --workspace ${{ env.CARGO_FLAGS }} -- -D warnings
      - name: Reproducibility
        if: matrix.rust == 'nightly'
        run: env RUSTFLAGS="--cfg reprocheck" cargo check --all-targets ${{ env.CARGO_FLAGS }}
      - name: Minver
        if: matrix.rust == 'nightly'
        run: |
          cargo update -Zdirect-minimal-versions
          cargo check ${{ env.CARGO_FLAGS }}

  msrv:
    runs-on: ubuntu-24.04
    name: MSRV
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88.0
      - name: Setup MSRV lock file
        run: cp Cargo.lock.msrv Cargo.lock
      - name: build
        run: cargo build

  fmt:
    runs-on: ubuntu-24.04
    name: Code format
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88.0
      - name: cargo-fmt
        run: |
          rustup component add rustfmt
          cargo fmt --check